### ISSUE TITLE
non-milestone build?

### ISSUE THREAD

**Issue by jkoelker** [flathub/org.freedesktop.Sdk.Extension.openjdk8#11]
I'm attempting to package [thinkorswim](https://www.tdameritrade.com/tools-and-platforms/thinkorswim/desktop/download.page), unfortunately they very strictly parse the `java -version` output and refuse to use any "milestone" release:

```
166:29.03.21 02:55:07:490 suit INFO: [UpdateManager-7228] checkRequireJRE_OrLaterInstalled: java version 1.8.0_282-adoptopenjdk
167:29.03.21 02:55:07:491 suit INFO: [UpdateManager-7228] checkRequireJRE_OrLaterInstalled: java version nok, need update to JRE 8update 11 or later
```

I've build the sdk locally setting the milestone to [`fcs`](https://github.com/AdoptOpenJDK/openjdk-build/blob/041c33c6a56ff3474133714c6d0ef6d7d9bce233/sbin/build.sh#L204) which appears to trigger a "production" build and was able to get `thinkorswim` to launch.

```
29.03.21 03:53:36:085 suit INFO: [UpdateManager-15829] checkRequireJRE_OrLaterInstalled: java version 1.8.0_282
29.03.21 03:53:36:086 suit INFO: [UpdateManager-15829] checkRequireJRE_OrLaterInstalled: java version ok
```

I'm by no means a java expert and I know there is some history with JDK8 and the milestone field being set for various uses, but if its possible to release an update, that would be super awesome!

**Comment by MatMaul** [comment]
Fixed, thanks.
