### ISSUE TITLE
Add 21.08 branch

### ISSUE THREAD

**Issue by Newbytee** [flathub/org.freedesktop.Sdk.Extension.openjdk8#13]
One of the packages I maintain ([com.jpexs.decompiler.flash](https://github.com/flathub/com.jpexs.decompiler.flash)) use OpenJDK 8 as requested by upstream. I would like to be able to upgrade this package to use the 21.08 runtime, but currently I can't since OpenJDK 8 isn't available there.

**Comment by cxrvh** [comment]
I've created an updated [branch/21.08](https://github.com/cxrvh/org.freedesktop.Sdk.Extension.openjdk8/tree/branch/21.08) which now uses Eclipse Adoptium. Would be great if someone could take a look at it (@MatMaul ?). **The branch was only built & tested for x86_64!**

I'm not sure if the aarch64 change should be applied to 20.08, too.

**Comment by TingPing** [comment]
I made the branch here if you can open a pr to it.

**Comment by cxrvh** [comment]
OpenJDK 8 was released for 21.08, this issue can be closed.
