### ISSUE TITLE
Add 22.08 branch

### ISSUE THREAD

**Issue by Newbytee** [flathub/org.freedesktop.Sdk.Extension.openjdk8#24]
Same as last year (https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8/issues/13). One of the packages I maintain ([com.jpexs.decompiler.flash](https://github.com/flathub/com.jpexs.decompiler.flash)) use OpenJDK 8 as requested by upstream. I would like to be able to upgrade this package to use the 22.08 runtime, but currently I can't since OpenJDK 8 isn't available there.

**Comment by cxrvh** [comment]
I've created an updated [branch/22.08](https://github.com/cxrvh/org.freedesktop.Sdk.Extension.openjdk8/tree/branch/22.08). As always, the branch was only built & tested for x86_64!

I'll create a pull request when the branch is created here (@MatMaul , @TingPing ?).

**Comment by MatMaul** [comment]
Hi, thanks for that ! I've just push a 22.08 branch with no modifications, please push your PR there :)

**Comment by Newbytee** [comment]
Tested the 22.08 branch with com.jpexs.decompiler.flash and it seems to work just fine! :partying_face:

Thanks for fixing this.
