### ISSUE TITLE
Add branch/23.08

### ISSUE THREAD

**Issue by cxrvh** [flathub/org.freedesktop.Sdk.Extension.openjdk8#36]
openjdk8 should be build for 23.08 when the new runtime is released.
I've already prepared a [branch](https://github.com/cxrvh/org.freedesktop.Sdk.Extension.openjdk8/tree/branch/23.08) for the current 23.08beta which can be updated after the release.

**Comment by Newbytee** [comment]
Just to show that there is interest in this, https://github.com/flathub/com.jpexs.decompiler.flash needs it.

**Comment by cxrvh** [comment]
The branch has been updated for 23.08.

**Comment by Newbytee** [comment]
> The branch has been updated for 23.08.

Where?

**Comment by cxrvh** [comment]
@Newbytee I've updated my private repository for the final release of the runtime.

There is now a draft pull request to track this together with the other updates.

**Comment by hfiguiere** [comment]
merged #37 
the branch was effectively building the wrong version.
