### ISSUE TITLE
Freedesktop SDK 24.08 will be dropping appstream-compose

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.freedesktop.Sdk.Extension.openjdk8#43]
Please remove manual compose or switch to appstreamcli 

See https://docs.flatpak.org/en/latest/extension.html#extension-manifest for the commands

**Comment by guihkx** [comment]
Done in https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8/commit/bc5262313ebcd956dcda3361d7efcc4e7ffa538d
