### ISSUE TITLE
Add a 24.08 branch

### ISSUE THREAD

**Issue by A6GibKm** [flathub/org.freedesktop.Sdk.Extension.openjdk8#50]
Required for https://github.com/flathub/cc.arduino.arduinoide.

To be honest, I am not familiar to how openjdk releases work so I am not sure if it makes to update openjdk8 until the end of time.

**Comment by guihkx** [comment]
Done in https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8/commit/bc5262313ebcd956dcda3361d7efcc4e7ffa538d
